#########################################################################################################################################################
#                                                                                                                                                       #
#$$$$$$$\  $$$$$$$$\ $$$$$$$$\ $$$$$$$$\ $$$$$$$$\ $$$$$$$\         $$$$$$\  $$\   $$\ $$\   $$\ $$$$$$$$\ $$$$$$$\   $$$$$$\  $$\      $$\ $$\   $$\   #
#$$  __$$\ $$  _____|\__$$  __|\__$$  __|$$  _____|$$  __$$\       $$  __$$\ $$ |  $$ |$$ |  $$ |\__$$  __|$$  __$$\ $$  __$$\ $$ | $\  $$ |$$$\  $$ |  #
#$$ |  $$ |$$ |         $$ |      $$ |   $$ |      $$ |  $$ |      $$ /  \__|$$ |  $$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ /  $$ |$$ |$$$\ $$ |$$$$\ $$ |  #
#$$$$$$$\ |$$$$$\       $$ |      $$ |   $$$$$\    $$$$$$$  |      \$$$$$$\  $$$$$$$$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |  $$ |$$ $$ $$\$$ |$$ $$\$$ |  #
#$$  __$$\ $$  __|      $$ |      $$ |   $$  __|   $$  __$$<        \____$$\ $$  __$$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |  $$ |$$$$  _$$$$ |$$ \$$$$ |  #
#$$ |  $$ |$$ |         $$ |      $$ |   $$ |      $$ |  $$ |      $$\   $$ |$$ |  $$ |$$ |  $$ |   $$ |   $$ |  $$ |$$ |  $$ |$$$  / \$$$ |$$ |\$$$ |  #
#$$$$$$$  |$$$$$$$$\    $$ |      $$ |   $$$$$$$$\ $$ |  $$ |      \$$$$$$  |$$ |  $$ |\$$$$$$  |   $$ |   $$$$$$$  | $$$$$$  |$$  /   \$$ |$$ | \$$ |  #
#\_______/ \________|   \__|      \__|   \________|\__|  \__|       \______/ \__|  \__| \______/    \__|   \_______/  \______/ \__/     \__|\__|  \__|  #
#.______   ____    ____           __    ______        _______. _______ .______       __________   ___    __    _____                                    #
#|   _  \  \   \  /   /          |  |  /  __  \      /       ||   ____||   _  \     |   ____\  \ /  /   / /   | ____|                                   #
#|  |_)  |  \   \/   /           |  | |  |  |  |    |   (----`|  |__   |  |_)  |    |  |__   \  V  /   / /_   | |__                                     #
#|   _  <    \_    _/      .--.  |  | |  |  |  |     \   \    |   __|  |      /     |   __|   >   <   | '_ \  |___ \                                    #
#|  |_)  |     |  |        |  `--'  | |  `--'  | .----)   |   |  |____ |  |\  \----.|  |____ /  .  \  | (_) |  ___) |                                   #
#|______/      |__|         \______/   \______/  |_______/    |_______|| _| `._____||_______/__/ \__\  \___/  |____/                                    #
#                                                                                                                                                       #
#########################################################################################################################################################

#Server configuration(Messages and commands)
Server:
  #Use § instead of &
  LeaveMessage: §aSending you to a lobby server...
  Restarting: §4The server is being restarting. Kicked to lobby
  #=================================================================================================================================================================
  #You don't have to put '/'. If you put it the command will be '//command'.
  LeaveCommand: leave 
  #IN NEXT VERSION
  StopCommand: stop 
  #IN NEXT VERSION
  #=================================================================================================================================================================
  #Stop command cannot be changed, if you change it, everyone will have access to it(it's protected if you change it. You will be able to change it in next update.)
  #Servers to kick to(you can put unlimited servers, if you put more than one, it will choose one ramdoly)
  ToKick:
    - lobby1
    - lobby2
